INFO - 39_capture_logs.py - 2025-02-07 17:06:18,045 - This is INFO
DEBUG - 39_capture_logs.py - 2025-02-07 17:06:18,047 - This is DEBUG
ERROR - 39_capture_logs.py - 2025-02-07 17:06:18,047 - This is ERROR
WARNING - 39_capture_logs.py - 2025-02-07 17:06:18,048 - This is WARNING
CRITICAL - 39_capture_logs.py - 2025-02-07 17:06:18,048 - This is CRITICAL
INFO - 39_capture_logs.py - 2025-02-07 17:06:18,049 - Reached try block
INFO - 39_capture_logs.py - 2025-02-07 17:06:18,049 - Opening file..
INFO - 39_capture_logs.py - 2025-02-07 17:06:18,049 - Reached except block
ERROR - 39_capture_logs.py - 2025-02-07 17:06:18,049 - Got Error and Details are: [Errno 2] No such file or directory: 'D:\\sndkjaj\\ashdjsd.txt'
INFO - 39_capture_logs.py - 2025-02-07 17:06:18,049 - Reached end of except block
